### ISSUE TITLE
BracketDotKeySplitter always treats the value between bracket as literal?

### ISSUE THREAD

**Issue by rmuller** [trimou/trimou#116]
When using `BracketDotKeySplitter`

`{{map["b"]}}`, `{{map['b']}}` and `{{map[b]}}` all yield the same result, treating "b" as a literal String igoring if  "b" is an key/expression. Is this the intended behavior?

**Comment by mkouba** [comment]
Yes, this is expected. `KeySplitter` is only responsible for splitting a key, e.g. `foo.bar` => `["foo", "bar"]`. No evaluation. In your example, `map[b]` is translated to `["map", "bar"]`. The original reason for `BracketDotKeySplitter` was to allow to use dots in a part of a key, so that e.g. `messages["my.message.key"]` is translated to `["messages", "my.message.key"]`. 

`EvalHelper` together with `BracketDotNotation` might be used to handle your use case:
https://github.com/trimou/trimou/blob/master/core/src/test/java/org/trimou/handlebars/EvalHelperTest.java#L58

**Comment by rmuller** [comment]
> The original reason for BracketDotKeySplitter was to allow to use dots in a part of a key

Okay, that makes sense. Also thanks for the suggestion. Will try it out.
