### ISSUE TITLE
#if and #each vs. pure Mustache blocks

### ISSUE THREAD

**Issue by hwellmann** [trimou/trimou#51]
This is just a question and not a real problem (I hope):

Are Handlebars helpers like `#if` and `#each` a functional extension or just syntactical sugar?
In other words, is the output of

```
{{#myScalar}}...{{/myScalar}}
{{#myCollection}}...{{/myCollection}}
```

any different from

```
{{#if myScalar}}...{{/if}}
{{#each myCollection}}...{{/each}}
```

**Comment by mkouba** [comment]
Not really, there are slight differences. For mustache section, the content is **not rendered** if the context object is:
* null
* false
* an empty array or `Iterable`

Otherwise the content is rendered one or more times, see `org.trimou.engine.segment.SectionSegment` for more info.

On the other hand, for `if` helper, the content is **not rendered** if the context object is falsy, i.e. null, false, empty array or `Iterable`, `CharSequence` of length 0, `Number` of value 0. Of course, `if` helper does never push the context object on the stack (aka nested context).

Moreover trimou's `if` helper may evaluate multiple params.

**Comment by mkouba** [comment]
And of course you can easily implement your own helpers which will follow the pure Mustache logic...

**Comment by hwellmann** [comment]
Thanks for clarifying! The point that `#if` doesn't push the context is important, I hadn't realized that. And now I've found the examples in the `IfHelper` Javadoc.

I think it would be helpful for new users to include some more examples in the Documentation, especially for people who know little or nothing about Mustache or Handlebars (including myself).

In fact, I'm afraid the very first paragraph on http://trimou.org/ is hardly sufficient to convey the idea of Trimou, and mentioning `*.js` in a Java context is often sufficient to scare people away.

BTW, I hadn't heard about Trimou until last week via [this article](http://www.javaworld.com/article/2449436/java-web-development/in-praise-of-java-template-engines.html), after getting frustrated with ANTLR's StringTemplate.

I find Trimou suits my use cases much better, its documentation is more user-friendly, and above all, its source code is a lot cleaner, more readable and engineered.

**Comment by mkouba** [comment]
@hwellmann I'm glad to hear trimou helps! Yes, there should be more examples... But keeping the documentation up-to-date it not for free. So I would recommend to look at our [examples](https://github.com/trimou/trimou/tree/master/examples) and tests (both unit and integration). Thanks for your interest and always feel free to contribute!
